// Generated by gencpp from file myrobot_msgs/led.msg
// DO NOT EDIT!


#ifndef MYROBOT_MSGS_MESSAGE_LED_H
#define MYROBOT_MSGS_MESSAGE_LED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace myrobot_msgs
{
template <class ContainerAllocator>
struct led_
{
  typedef led_<ContainerAllocator> Type;

  led_()
    : command()  {
    }
  led_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::myrobot_msgs::led_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::myrobot_msgs::led_<ContainerAllocator> const> ConstPtr;

}; // struct led_

typedef ::myrobot_msgs::led_<std::allocator<void> > led;

typedef boost::shared_ptr< ::myrobot_msgs::led > ledPtr;
typedef boost::shared_ptr< ::myrobot_msgs::led const> ledConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::myrobot_msgs::led_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::myrobot_msgs::led_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace myrobot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'myrobot_msgs': ['/home/gong/\xe6\xa1\x8c\xe9\x9d\xa2/myrobot/src/myrobot_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::myrobot_msgs::led_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::myrobot_msgs::led_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myrobot_msgs::led_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::myrobot_msgs::led_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myrobot_msgs::led_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::myrobot_msgs::led_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::myrobot_msgs::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::myrobot_msgs::led_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::myrobot_msgs::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "myrobot_msgs/led";
  }

  static const char* value(const ::myrobot_msgs::led_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::myrobot_msgs::led_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string command\n\
";
  }

  static const char* value(const ::myrobot_msgs::led_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::myrobot_msgs::led_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct led_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::myrobot_msgs::led_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::myrobot_msgs::led_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MYROBOT_MSGS_MESSAGE_LED_H
